// console.log(process.env)
// console.log(process.env.roma)
// console.log(process.env.vita)
// console.log(process.env.NODE_ENV)
// console.log(process.argv)
// require('./calculator')
require('./filesApp')
